language: cpp

before_install:
  - sudo add-apt-repository -y ppa:h-rayflood/llvm
  - sudo apt-get update -qq
  - sudo apt-get install --allow-unauthenticated -qq libboost-dev swi-prolog clang-3.2 clang-3.2-dev python-pip
  - sudo pip install lit

compiler:
  - gcc

before_script:
  - mkdir build
  - cd build

script:
  - cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..
  - make all check
